import { Vacancy } from '../types/vacancy';

export let mockVacancies: Vacancy[] = [
  {
    id: 1,
    vacancyTitle: 'Java Backend Developer',
    department: 'IT Department',
    fullTime: true,
    description: 'This is a job description.',
    salary: 65000,
    company: 'Bosch AG',
    createdAt: '08.10.2023',
    updatedAt: '12.10.2023',
  },
  {
    id: 2,
    vacancyTitle: 'Web Developer (React, Angular)',
    department: 'IT Department',
    fullTime: true,
    description: 'This is a great job description for a great job.',
    salary: 63000,
    company: 'Bosch AG',
    createdAt: '08.10.2023',
    updatedAt: '12.10.2023',
  },
  {
    id: 3,
    vacancyTitle: 'Frontend Developer',
    department: 'IT Department',
    fullTime: true,
    description: 'This is a job description.',
    salary: 75000,
    company: 'Bosch AG',
    createdAt: '08.10.2023',
    updatedAt: '12.10.2023',
  },
  {
    id: 4,
    vacancyTitle: 'Database Administrator',
    department: 'IT Department',
    fullTime: true,
    description: 'This is a job description.',
    salary: 52000,
    company: 'Bosch AG',
    createdAt: '08.10.2023',
    updatedAt: '12.10.2023',
  },
  {
    id: 5,
    vacancyTitle: 'Financial Analyst',
    department: 'Finance Department',
    fullTime: true,
    description: 'This is a job description.',
    salary: 50000,
    company: 'Bosch AG',
    createdAt: '08.10.2023',
    updatedAt: '12.10.2023',
  },
  {
    id: 6,
    vacancyTitle: 'SAP Developer',
    department: 'IT Department',
    fullTime: true,
    description: 'This is a job description.',
    salary: 50000,
    company: 'Bosch AG',
    createdAt: '08.10.2023',
    updatedAt: '12.10.2023',
  },
  {
    id: 7,
    vacancyTitle: 'Team Lead for Product X',
    department: 'IT Department',
    fullTime: true,
    description: 'This is a job description.',
    salary: 50000,
    company: 'Bosch AG',
    createdAt: '08.10.2023',
    updatedAt: '12.10.2023',
  },
  {
    id: 8,
    vacancyTitle: 'Procurement Manager',
    department: 'Procurement Department',
    fullTime: true,
    description: 'This is a job description.',
    salary: 50000,
    company: 'Bosch AG',
    createdAt: '08.10.2023',
    updatedAt: '12.10.2023',
  },
  {
    id: 9,
    vacancyTitle: 'HR Recruiter',
    department: 'HR Department',
    fullTime: true,
    description:
      'This is a job description. This is a super special and very important job. We desperately need someone for this job. Please apply for this job. We need you!',
    salary: 50000,
    company: 'Bosch AG',
    createdAt: '08.10.2023',
    updatedAt: '12.10.2023',
  },
  {
    id: 10,
    vacancyTitle: 'IT Security Specialist',
    department: 'IT Department',
    fullTime: true,
    description: 'This is a job description.',
    salary: 50000,
    company: 'Bosch AG',
    createdAt: '08.10.2023',
    updatedAt: '12.10.2023',
  },
  {
    id: 11,
    vacancyTitle: 'Hardware Engineer',
    department: 'Hardware Development Department',
    fullTime: true,
    description: 'This is a job description.',
    salary: 50000,
    company: 'Bosch AG',
    createdAt: '08.10.2023',
    updatedAt: '12.10.2023',
  },
  {
    id: 12,
    vacancyTitle: 'Forklift Driver',
    department: 'Logistics Department',
    fullTime: true,
    description: 'This is a job description.',
    salary: 30000,
    company: 'Bosch AG',
    createdAt: '08.10.2023',
    updatedAt: '12.10.2023',
  },
  {
    id: 13,
    vacancyTitle: 'IT Security Specialist',
    department: 'IT Department',
    fullTime: true,
    description: 'This is a job description.',
    salary: 50000,
    company: 'Bosch AG',
    createdAt: '08.10.2023',
    updatedAt: '12.10.2023',
  },
  {
    id: 14,
    vacancyTitle: 'IT Security Specialist',
    department: 'IT Department',
    fullTime: true,
    description: 'This is a job description.',
    salary: 50000,
    company: 'Bosch AG',
    createdAt: '08.10.2023',
    updatedAt: '12.10.2023',
  },
  {
    id: 15,
    vacancyTitle: 'Software Architect',
    department: 'IT Department',
    fullTime: true,
    description: 'This is a job description.',
    salary: 50000,
    company: 'Bosch AG',
    createdAt: '08.10.2023',
    updatedAt: '12.10.2023',
  },
  {
    id: 16,
    vacancyTitle: 'Software Architect',
    department: 'IT Department',
    fullTime: true,
    description: 'This is a job description.',
    salary: 50000,
    company: 'Bosch AG',
    createdAt: '08.10.2023',
    updatedAt: '12.10.2023',
  },
];
